// Generated by gencpp from file lcsr_nettools/TopicStatistics.msg
// DO NOT EDIT!


#ifndef LCSR_NETTOOLS_MESSAGE_TOPICSTATISTICS_H
#define LCSR_NETTOOLS_MESSAGE_TOPICSTATISTICS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <lcsr_nettools/TopicMeasurements.h>
#include <lcsr_nettools/TopicMeasurements.h>

namespace lcsr_nettools
{
template <class ContainerAllocator>
struct TopicStatistics_
{
  typedef TopicStatistics_<ContainerAllocator> Type;

  TopicStatistics_()
    : header()
    , topic_name()
    , recent_buffer_duration()
    , recent()
    , all_time()  {
    }
  TopicStatistics_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , topic_name(_alloc)
    , recent_buffer_duration()
    , recent(_alloc)
    , all_time(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _topic_name_type;
  _topic_name_type topic_name;

   typedef ros::Duration _recent_buffer_duration_type;
  _recent_buffer_duration_type recent_buffer_duration;

   typedef  ::lcsr_nettools::TopicMeasurements_<ContainerAllocator>  _recent_type;
  _recent_type recent;

   typedef  ::lcsr_nettools::TopicMeasurements_<ContainerAllocator>  _all_time_type;
  _all_time_type all_time;





  typedef boost::shared_ptr< ::lcsr_nettools::TopicStatistics_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::lcsr_nettools::TopicStatistics_<ContainerAllocator> const> ConstPtr;

}; // struct TopicStatistics_

typedef ::lcsr_nettools::TopicStatistics_<std::allocator<void> > TopicStatistics;

typedef boost::shared_ptr< ::lcsr_nettools::TopicStatistics > TopicStatisticsPtr;
typedef boost::shared_ptr< ::lcsr_nettools::TopicStatistics const> TopicStatisticsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::lcsr_nettools::TopicStatistics_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::lcsr_nettools::TopicStatistics_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace lcsr_nettools

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'lcsr_nettools': ['/home/shamaine/catkin_ws/src/lcsr_nettools/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::lcsr_nettools::TopicStatistics_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::lcsr_nettools::TopicStatistics_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::lcsr_nettools::TopicStatistics_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::lcsr_nettools::TopicStatistics_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lcsr_nettools::TopicStatistics_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lcsr_nettools::TopicStatistics_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::lcsr_nettools::TopicStatistics_<ContainerAllocator> >
{
  static const char* value()
  {
    return "414ca0d7c2276abebacb6812196057cd";
  }

  static const char* value(const ::lcsr_nettools::TopicStatistics_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x414ca0d7c2276abeULL;
  static const uint64_t static_value2 = 0xbacb6812196057cdULL;
};

template<class ContainerAllocator>
struct DataType< ::lcsr_nettools::TopicStatistics_<ContainerAllocator> >
{
  static const char* value()
  {
    return "lcsr_nettools/TopicStatistics";
  }

  static const char* value(const ::lcsr_nettools::TopicStatistics_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::lcsr_nettools::TopicStatistics_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n\
\n\
string topic_name\n\
duration recent_buffer_duration\n\
\n\
lcsr_nettools/TopicMeasurements recent\n\
lcsr_nettools/TopicMeasurements all_time\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: lcsr_nettools/TopicMeasurements\n\
float64 msg_loss\n\
time first_recv_time\n\
time latest_recv_time\n\
lcsr_nettools/StatisticsMeasurements latency\n\
lcsr_nettools/StatisticsMeasurements frequency\n\
\n\
================================================================================\n\
MSG: lcsr_nettools/StatisticsMeasurements\n\
float64 avg\n\
float64 std\n\
float64 min\n\
float64 max\n\
";
  }

  static const char* value(const ::lcsr_nettools::TopicStatistics_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::lcsr_nettools::TopicStatistics_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.topic_name);
      stream.next(m.recent_buffer_duration);
      stream.next(m.recent);
      stream.next(m.all_time);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TopicStatistics_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::lcsr_nettools::TopicStatistics_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::lcsr_nettools::TopicStatistics_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "topic_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.topic_name);
    s << indent << "recent_buffer_duration: ";
    Printer<ros::Duration>::stream(s, indent + "  ", v.recent_buffer_duration);
    s << indent << "recent: ";
    s << std::endl;
    Printer< ::lcsr_nettools::TopicMeasurements_<ContainerAllocator> >::stream(s, indent + "  ", v.recent);
    s << indent << "all_time: ";
    s << std::endl;
    Printer< ::lcsr_nettools::TopicMeasurements_<ContainerAllocator> >::stream(s, indent + "  ", v.all_time);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LCSR_NETTOOLS_MESSAGE_TOPICSTATISTICS_H
